apps/order/urls.py
from django.conf.urls import url
from apps.order import views

urlpatterns = [
	url(r'^cart/order/$', views.CartOrderHandler,name='cart_order'),
	url(r'^cart/submit_order/$', views.OrderSubmitHandler, name="submit_order"),
	url(r'^cart/view_order/$', views.OrderViewHandler, name="view_order"),
	url(r'^cart/hide_order/$', views.OrderHideHandler, name="hide_order"),
]

dj_Book/urls.py
from django.conf.urls import url,include
import xadmin
from django.views.generic.base import RedirectView

from apps.order.pay_helper import pay

urlpatterns = [
    url('xadmin/', xadmin.site.urls),
    url(r'^$',  RedirectView.as_view(url="/book/index"),name='index'),
    url(r'^book/', include("book.urls",namespace='art')),
    url(r'^comment/', include("comment.urls",namespace='comment')),
    url(r'^message/', include("message.urls",namespace='message')),
    url(r'^order/', include("order.urls",namespace='order')),
    url(r'^cart/', include("cart.urls",namespace='cart')),
    url(r'^user/', include("user.urls",namespace='user')),
    url(r'^apis/', include("apis.urls")),
    url(r'^analyze/', include("analyze.urls",namespace='analyze')),
    url(r'^search/', include('haystack.urls',namespace='search')),
    url(r'^captcha', include('captcha.urls')),
    url(r'^ueditor/',include('DjangoUeditor.urls'))
]

extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

apps/order/models.py
from django.db import models
from django.utils import timezone
from dj_Book.settings import  PAY_CHOICES
from apps.book.models import Art
# from DjangoUeditor.models import UEditorField
from apps.user.models import ArtsUser

'''
订单数据模型
'''
class ProductOrder(models.Model):
	order_id = models.BigIntegerField(verbose_name="订单号", unique=True)
	pay_type = models.IntegerField(default=0, verbose_name="支付类型", choices=PAY_CHOICES)
	address = models.CharField(default='', max_length=200, verbose_name="订单配送地址")
	phone = models.BigIntegerField(default=0, verbose_name="联系方式")
	order_time = models.DateTimeField(default=timezone.now, db_index=True,verbose_name="下单时间")
	user = models.ForeignKey(ArtsUser,verbose_name="用户")
	flag = models.IntegerField(verbose_name="是否隐藏",default=0)

	def __str__(self):
		return self.order_id


	class Meta:
		db_table = "product_order"
		verbose_name = "用户订单"
		verbose_name_plural = verbose_name


class OrderItem(models.Model):
	order = models.ForeignKey(ProductOrder,verbose_name='订单号')
	product = models.ForeignKey(Art,verbose_name='商品编号')
	user = models.ForeignKey(ArtsUser, verbose_name="购买用户")
	quantity =  models.CharField(max_length=10)

	class Meta:
		db_table = "order_item"
		verbose_name = "订单商品"
		verbose_name_plural = verbose_name

apps/order/forms.py
from django import forms
from django.forms import widgets
from dj_Book.settings import PAY_CHOICES

'''
订单表单
'''
class  OrderForms(forms.Form):
	address =  forms.CharField(
      label="配送地址",
      required=True,
      widget=widgets.TextInput(
         attrs={
            "class": "form-control",
            "placeholder": "请输入配送地址",
         }),
      error_messages={
         "required": "对不起，配送地址不能为空！",
      }
   )
	pay_type = forms.ChoiceField(
      label="支付方式",
      required=True,
      choices=PAY_CHOICES,
      widget=forms.RadioSelect()
   )
	phone = forms.CharField(
      label="手机",
      required=True,
      widget=widgets.TextInput(
         attrs={
            "class": "form-control",
            "placeholder": "请输入手机",
         }),
      error_messages={
         "required": "对不起，手机不能为空！",
      }
   )

apps/order/views.py
from alipay import AliPay
from django.db.models import Q
from django.shortcuts import render, redirect
from django.urls import reverse

from apps.cart.models import LineItem,Cart,OrderItemRelation
from apps.order.models import OrderItem,ProductOrder
from apps.book.models import Art
from dj_Book import settings
from dj_Book.utils import check_user_login, flash, create_order_id
from apps.order import forms
from django.views.decorators.csrf import csrf_exempt

'''
订单功能
'''
@check_user_login
def CartOrderHandler(request):
	user = request.session.get("muser")
	# 从购物车表中获取商品信息
	(total_price, product_list) = Cart.get_products(user)
	# 获取已经写好的订单表单
	order_form = forms.OrderForms()

	context = dict(
		user = user,
		total_price = total_price,
		product_list = product_list,
		form = order_form,
	)
	return render(request, "submit_order.html", context=context)


'''
提交订单功能
'''
@csrf_exempt
@check_user_login
def OrderSubmitHandler(request):
	url = request.path
	print(f"OrderSubmitHandler submit ok {url}")
	if request.method == "POST":
		order_form = forms.OrderForms(data=request.POST)
		if not order_form.is_valid():
			flash(request, "error", f"用户提交订单失败！")
			return CartOrderHandler(request)
		# cleaned_data中的值类型与字段定义的Field类型一致
		address = order_form.cleaned_data.get("address")
		pay_type = int(order_form.cleaned_data.get("pay_type"))
		phone = int(order_form.cleaned_data.get("phone"))
		order_id = create_order_id()
		user = request.session.get("muser")

		prod_order = ProductOrder(order_id=order_id, address=address, pay_type=pay_type, phone=phone,user_id=user.id)
		prod_order.save()

		# 得到当前用户的购物车的商品信息
		line_items = LineItem.objects.filter(Q(user=user.id) & Q(flag=0))
		# 将订单购物车关系表持久化
		[OrderItemRelation(line_item_id=int(line_item.id), product_order_id=prod_order.id).save()  for  line_item  in  line_items]
		# 将订单的商品持久化
		order = ProductOrder.objects.filter(order_id=order_id).first()
		[OrderItem(quantity=line_item.quantity,order_id=order.id,product_id=line_item.product_id,user_id=user.id).save() for line_item  in  line_items ]

		flash(request, "success", f"用户提交订单成功!,订单号为:{order_id}")

		"""开始支付"""
		amount = request.POST.get('amount')
		trad_no = order_id
		alipay = AliPay(
			appid=settings.APP_ID,
			app_notify_url='http://127.0.0.1/pay/notify/',
			app_private_key_path=settings.APP_PRIVATE_KEY_PATH,
			alipay_public_key_path=settings.ALIPAY_PUBLIC_KEY_PATH,
			sign_type='RSA2',
			debug=True
		)
		# 生成订单参数
		# 电脑网站的支付地址  https://openapi.alipaydev.com/gateway.do?order_url
		order_url = alipay.api_alipay_trade_page_pay(
			subject='爱尚书城订单',
			out_trade_no=trad_no,
			total_amount=amount,
			return_url='https://127.0.0.1/',  # 支付成功后前端跳转的网址
			notify_url='后台接收支付宝支付相关信息的接口 post请求'
		)
		pay_url = settings.ALT_PAY_DEV_URL + order_url
		return redirect(pay_url)

	return CartOrderHandler(request)





'''
查看订单功能
'''
@csrf_exempt
@check_user_login
def OrderViewHandler(request):
	user = request.session.get("muser")
	uid = user.id
	orders = ProductOrder.objects.order_by('-order_time').filter(Q(user_id=uid) & Q(flag=0))
	for order in orders:
		order.items = OrderItem.objects.filter(order_id=order.id)
		order.price = 0
		for order.item in order.items:
			order.item.art =  Art.objects.filter(id=order.item.product_id).first()
			order.item.price = int(order.item.art.a_price) * int(order.item.quantity)
			order.price += order.item.price

	context = {
		'orders':orders,
		'user':user
	}
	return render(request, 'view_order.html', context)

'''
删除订单功能
'''
@csrf_exempt
@check_user_login
def OrderHideHandler(request):
	oid = request.GET.get('oid')
	productorder = ProductOrder.objects.filter(id=oid).first()
	productorder.flag = 1
	productorder.save()

	return redirect(reverse('order:view_order'))

"""子表查询母表(多--->>>1)"""
# 写法1:子表对象.母表表名的小写.母表字段名
# products = line_item.art.objects.all()
# 写法2:子表名小写__子表字段="xxx"
# products = Art.objects.get(lineitem__orderitemrelation__product_order_id='')

"""母表查询子表(1--->>>多)"""
# # 写法1：子表小写_set的写法
# Art.objects.get(t_id='').art_content_set.all()
# # 写法2(推荐)： 写法：filter(子表外键字段__母表字段='过滤条件')
# Art.objects.filter(lineitem__orderitemrelation__product_order_id='')
# # 写法3:(原始写法,不推荐)
# art_id = Art.objects.get(t_id='').id

apps/order/templates/submit_order.html
{% extends "base_tmp.html" %}

{% block content %}

    <!--内容-->
    <div class="container" style="margin-top:76px">
        <div class="row">
            {#主页部分#}
            <div class="col-md-8">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3 class="panel-title"><span class="glyphicon glyphicon-list-alt"></span>{{ user.username }}的订单
                        </h3>
                    </div>
                    <div class="panel-body">

                        <form action="{% url 'order:submit_order' %}" method="post" class="smart-green">

                            <div class="col-md-8">
                                <h3 style="color: red"><span class="glyphicon glyphicon-hand-right"></span>订单配送信息</h3>
                                {{ form.as_p }}

                         {% if messages %}
                           <ul>
                              {% for msg in messages %}
                                <li style="color: red">{{msg.message}}</li>
                               {% endfor %}
                           </ul>
                        {% endif %}

                            </div>

                            <hr>
                            <div class="col-md-9">
                             <hr>
                                <h3 style="color: red"><span class="glyphicon glyphicon-hand-right"></span>订单的购物车信息</h3>
                                <table class="table" style="border: 1px;">
                                    <thead>
                                    <tr>
                                        <th class="yellow header">名称</th>
                                        <th class="header">数量</th>
                                        <th class="blue header">单价</th>
                                        <th class="green header">小计</th>

                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for item in product_list %}
                                        {# 购物车选中的商品的信息#}
                                        {% if item.flag == 0 %}
                                            <tr>
                                                <td>{{ item.product.a_title }}</td>
                                                <th>{{ item.quantity }}</th>
                                                <td>{{ item.unit_price }}</td>
                                                <td>{% widthratio item.quantity 1 item.unit_price %}</td>
                                            </tr>
                                        {% endif %}
                                    {% endfor %}
                                    <tr style="color: green">
                                        <th></th>
                                        <td></td>
                                        <th>总计：</th>
                                        <th>{{ total_price }}<input type="text" hidden value={{ total_price }} name='amount'></th>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>

                            <div class="col-md-12">
                                <div class="col-md-3">
                                    <!--
                                    <a class="btn  btn-success" href="/art/cart/check_order">确认订单</a></p>
                                    -->
                                    <input type="submit" class="button btn  btn-success" value="提交订单"/>
                                </div>
                                <div class="col-md-3">
                                    <a class="btn  btn-danger" type="button" href="{% url 'art:index' %}">继续购物</a></a></p>
                                </div>
                            </div>

                        </form>
                    </div>

                </div>

            </div>

            {# 推荐部分#}
            <div class="col-md-4 filebox" >
                <div class="recommend "></div>
            </div>
        </div>
    </div>

{% endblock %}

{% block js %}
<script language="JavaScript">
    $(document).ready(function () {
        let url = 'http://127.0.0.1:9000/apis/booklist/';
        $.get(url,function (results) {
            books = results;
            show_recommends(books);
        })
    });

    function show_recommends(books) {
       for(let book of books){
           let img_url =  'http://127.0.0.1:9000/static/imgs/full/' + book.a_img_url_figer + '.jpg';
            $('.recommend')
                .append(
                $('<div>').css({width:'110px',marginRight:'10px',marginBottom:'20px'}).addClass('pull-left')
                    .append(
                        $('<img>').css({height:'150px',width:'100%'}).attr('src',img_url)
                    )
                    .append(
                        $('<div>').css({height:'30px',width:'100%',background:'#2672ec'}).addClass('text-center')
                            .append(
                                $('<a>').text('立即阅读 ').css({color:' white',fontSize:'large'})
                            )
                    )
            )
       }
    }
</script>
{% endblock %}

apps/order/templates/view_order.html
{% extends "base_tmp.html" %}

{% block content %}

<!--内容-->
<div class="container" style="margin-top:76px">
    <div class="row">
        {# 主页部分#}
        <div class="col-md-8">
        {% for order in orders %}

            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title"><span class="glyphicon glyphicon-list-alt"></span>{{user.username}}的订单</h3>
                </div>
                <div class="panel-body">

                        <div>
                            <h3>当前订单号:{{ order.order_id }}</h3>
                            <table class="table" style="border: 1px;">
                            <thead>
                            <tr>
                                <th class="yellow header">详情</th>
                                <th class="header">数量</th>
                                <th class="blue header">单价</th>
                                <th class="green header">小计</th>
                            </tr>
                            </thead>
                            {% for item in order.items %}
                            <tbody>
                            <tr>
                                <td>
                                    <div>
                                        <img src="/static/imgs/full/{{item.art.a_img_url_figer}}.jpg" style="height: 50px" class="pull-left">
                                        <div class="pull-left text-justify" style="margin-left: 10px">{{ item.art.a_title }}</div>
                                    </div>
                                </td>
                                 <td>{{item.quantity}}</td>
                                <td>{{item.art.a_price}}</td>
                                <td>{{item.price}}</td>
                            </tr>
                            {% endfor %}

                            <tr style="color: green">
                                <th></th>
                                <td></td>
                                <th>总计：</th>
                                <th>{{order.price}}</th>
                            </tr>
                            </tbody>

                        </table>
                        </div>

                        <div class="pull-right">
                            <a class="btn  btn-info" type="button" href="#">已完成订单</a>
                            <a class="btn  btn-danger" type="button" href="{% url 'order:hide_order' %}?oid={{ order.id }}">隐藏此订单</a>
                        </div>
                </div>
            </div>

        {% endfor %}

        </div>

        {# 推荐部分#}
        <div class="col-md-4">
             <div class="recommend "></div>
        </div>
    </div>
</div>

{% endblock %}

{% block js %}
<script language="JavaScript">
    $(document).ready(function () {
    });


</script>
{% endblock %}