apps/user/urls.py
from django.conf.urls import url
from apps.user import views

urlpatterns = [
    url(r"^register/$", views.RegisterHandler, name="register"),
	url(r"^login/$", views.LoginHandler, name="login"),
	url(r'^logout/$', views.LogoutHandler,name="logout"),
	url(r'^activate/$', views.ActivateHandler,name="activate"),
]

dj_Book/urls.py
from django.conf.urls import url,include
import xadmin
from django.views.generic.base import RedirectView

from apps.order.pay_helper import pay

urlpatterns = [
    url('xadmin/', xadmin.site.urls),
    url(r'^$',  RedirectView.as_view(url="/book/index"),name='index'),
    url(r'^book/', include("book.urls",namespace='art')),
    url(r'^comment/', include("comment.urls",namespace='comment')),
    url(r'^message/', include("message.urls",namespace='message')),
    url(r'^order/', include("order.urls",namespace='order')),
    url(r'^cart/', include("cart.urls",namespace='cart')),
    url(r'^user/', include("user.urls",namespace='user')),
    url(r'^apis/', include("apis.urls")),
    url(r'^analyze/', include("analyze.urls",namespace='analyze')),
    url(r'^search/', include('haystack.urls',namespace='search')),
    url(r'^captcha', include('captcha.urls')),
    url(r'^ueditor/',include('DjangoUeditor.urls'))
]

extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

apps/user/models.py
from django.db import models
from django.utils import timezone
from dj_Book.settings import SEX_CHOICES, DB_FIELD_VALID_CHOICES, USER_CHOICES,  DINNER_CHOICES, PAY_CHOICES
# from DjangoUeditor.models import UEditorField

'''
会员信息
'''
class  ArtsUser(models.Model):
	username = models.CharField(max_length=50, verbose_name="用户名")
	password = models.CharField(max_length=100, verbose_name="密码")
	email = models.EmailField(verbose_name="邮箱")
	createtime = models.DateTimeField(default=timezone.now, db_index=True, verbose_name="添加时间")
	flag = models.IntegerField(default=0, verbose_name="会员控制字段", choices=USER_CHOICES)

	def __str__(self):
		return self.username

	class Meta:
		db_table = "arts_user"
		verbose_name = "会员信息"
		verbose_name_plural = verbose_name
		ordering = ["-createtime"]

apps/user/forms.py
# -*- coding: utf-8 -*-

from django import forms
from captcha.fields import CaptchaField
from django.forms import widgets
from apps.user import models
from django.core.exceptions import ValidationError

'''
会员信息注册表单
基于数据模型ArtsUser
用户注册的信息会保存到cleaned_data
'''
class ArtsUserRegForm(forms.Form):
	username = forms.CharField(
		label = "用户名",
		required = True,
		min_length = 1,
		max_length = 10,
		widget = widgets.TextInput(
			attrs = {
				"class":"form-control",
				"placeholder":"请输入用户名，长度为1 ~ 10",
			}),
		error_messages = {
			"required": "对不起，输入的用户名不能为空",
			"min_length":"不行, 长度小于1",
			"max_length":"sorry, 长度大于10",
		}
	)
	password = forms.CharField(
		label =  "密码",
		required = True,
		min_length = 1,
		max_length = 10,
		widget = widgets.PasswordInput(
			attrs={
				"class":"form-control",
				"placeholder":"请输入密码, 长度为1~10",
			}),
		error_messages={
			"required": "密码不能为空",
			"min_length": "不行, 长度小于1",
			"max_length": "sorry, 长度大于10",
		}
	)
	email = forms.EmailField(
		label = "邮箱",
		required=True,
		widget=widgets.TextInput(
			attrs={
				"class": "form-control",
				"placeholder": "请输入邮箱",
			}),
		error_messages={
			"required": "邮箱不能为空",
		}
	)
	captcha = CaptchaField(label='验证码')


	def clean_username(self):
		#对会员信息的用户名username进行校验
		#此函数返回的结果会存到 cleaned_data
		username = self.cleaned_data.get("username", "")
		user_count = models.ArtsUser.objects.filter(username=username).count()
		if user_count:
			raise ValidationError("用户名已经存在！")
		return username



	def clean_email(self):
		#对会员信息的用户名username进行校验
		#此函数返回的结果会存到 cleaned_data
		email = self.cleaned_data.get("email", "")
		user_count = models.ArtsUser.objects.filter(email=email).count()
		if user_count:
			raise ValidationError("邮箱已经存在！")
		return email



'''
会员登录表单
'''
class ArtsUserLoginForm(forms.Form):
	username = forms.CharField(
		label="用户名",
		required=True,
		min_length=1,
		max_length=10,
		widget=widgets.TextInput(
			attrs={
				"class": "form-control",
				"placeholder": "请输入用户名，长度为1 ~ 10",
			}),
		error_messages={
			"required": "对不起，输入的用户名不能为空",
			"min_length": "不行, 长度小于1",
			"max_length": "sorry, 长度大于10",
		}
	)
	password = forms.CharField(
		label="密码",
		required=True,
		min_length=1,
		max_length=10,
		widget=widgets.PasswordInput(
			attrs={
				"class": "form-control",
				"placeholder": "请输入密码, 长度为1~10",
			}),
		error_messages={
			"required": "密码不能为空",
			"min_length": "不行, 长度小于1",
			"max_length": "sorry, 长度大于10",
		}
	)
	captcha = CaptchaField(label='验证码')

apps/user/views.py
from django.shortcuts import render, HttpResponseRedirect, HttpResponse, redirect
from apps.user import forms
from apps.user import models
from django.views.decorators.csrf import csrf_exempt

from dj_Book import settings
from dj_Book.utils import flash
from celery_tasks.tasks import send_register_active_email
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from captcha.models import CaptchaStore
from captcha.helpers import captcha_image_url

'''
加密算法：
可逆加密算法：BASE-64
不可逆加密算法: MD5
'''

'''
会员注册功能
支持方法：
GET --- 获取空注册表单
POST --- 提交注册表单
表单：forms.ArtsUserRegForm
数据模型:models.ArtsUser
'''
def create_pwd_md5(str_password):
	import hashlib
	h1 = hashlib.md5()
	h1.update(str_password.encode(encoding="utf-8"))
	return h1.hexdigest()


@csrf_exempt
def RegisterHandler(request):
	reg_form = forms.ArtsUserRegForm()
	method = request.method
	if method == "POST":
		reg_form = forms.ArtsUserRegForm(data=request.POST)
		if not reg_form.is_valid():
			#return HttpResponse("form is not valid")
			flash(request, "error", f"用户注册校验失败！")
			context = dict(form=forms.ArtsUserRegForm(data=request.POST))
			return render(request, "user_register.html", context=context)
		username = reg_form.cleaned_data.get("username")
		password = create_pwd_md5(reg_form.cleaned_data.get("password"))
		email = reg_form.cleaned_data.get("email")
		user = models.ArtsUser(username=username, password=password, email=email)
		user.save()
		flash(request, "success", f"恭喜，注册用户{username}成功！！")

		# 开始发送邮件(根据flag=0  : 表示未激活  flag=1  :  表示 激活)
		# 对用户的身份信息进行加密，生成激活token信息
		# serializer = Serializer('加解密密钥', '解密有效时间')
		serializer = Serializer(settings.SECRET_KEY, 3600 * 7)
		info = {'confirm': user.id}
		# # 调用dumps方法实现加密，返回值类型为bytes
		token = serializer.dumps(info)
		# 将其转换为str
		token = token.decode()
		send_register_active_email.delay(email, username, token)

	context = dict(form = reg_form)

	return render(request, "user_register.html", context=context)


@csrf_exempt
def LoginHandler(request):
	login_form = forms.ArtsUserLoginForm()
	if request.method == "POST":
		login_form = forms.ArtsUserLoginForm(data = request.POST)
		if not login_form.is_valid():
			flash(request, "error", f"用户登录校验失败！")
			context = dict(form=forms.ArtsUserLoginForm())
			return render(request, "user_login.html", context=context)
		username = login_form.cleaned_data.get("username")
		password = create_pwd_md5(login_form.cleaned_data.get("password"))
		user = models.ArtsUser.objects.filter(username=username, password=password)
		user_first = user.first()
		if user_first:  #登录验证成功，用户名和密码都正确
			request.session["muser"] = user_first
			return HttpResponseRedirect("/book/index")
		flash(request, "error", f"用户{username}登录失败！")

	context = dict(form = login_form)
	return render(request, "user_login.html", context=context)


def LogoutHandler(request):
	del request.session["muser"]
	return redirect('/')


def ActivateHandler(request):
	"""激活"""
	serializer = Serializer(settings.SECRET_KEY, 3600 * 7)
	try:
		token = request.GET.get('token')
		# # 调用loads方法实现解密
		info = serializer.loads(token)
		# 获取待激活用户id
		user_id = info['confirm']
		# 激活用户
		user = models.ArtsUser.objects.get(id=user_id)
		user.flag = 1
		user.save()

		# 跳转登录页面
		return redirect('/')
	except:
		# 激活链接已失效
		# 实际开发: 返回页面，让你点击链接再发激活邮件
		return HttpResponse('激活链接已失效')

apps/user/templates/user_login.html
{% extends "base_tmp.html" %}

{% block css %}

<link rel="stylesheet" href="/static/base/css/msg_style.css">
{% endblock %}

{% block content %}

    <!--内容-->
<div class="container" style="margin-top:76px">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-info">

                <div class="panel-heading">
                    <h3 class="panel-title">
                        <span class="glyphicon glyphicon-list-alt"></span>&nbsp;会员登录</h3>
                </div>

                <div class="panel-body">

                    <form action="{% url 'user:login' %}" method="post" class="smart-green">
                        <h1>用户登录</h1>
                        {{ form.as_p }}

                        验证码产生以下的html文件:
{#                        <input autocomplete="off" id="id_captcha_1" name="captcha_1" type="text">#}
{#                        <input id="id_captcha_0" name="captcha_0" type="hidden" value="hashkey ">#}
{#                        <img src="imgage_url" alt="captcha" class="captcha">#}




                        {% if messages %}
                           <ul>
                              {% for msg in messages %}
                                <li style="color: red">{{msg.message}}</li>
                               {% endfor %}
                           </ul>
                        {% endif %}

                        <div class="success-msg"></div>
                        <label>
                            <span>&nbsp;</span>
                            <input type="submit" class="button" value="提交登录"/>
                        </label>

                        <label>
                            <span>忘记账号？请点击 <a href="{% url 'user:register' %}">注册</a></span>
                        </label>

                    </form>

                </div>
            </div>
        </div>

    </div>
</div>
<!--内容-->
    
{% endblock %}

{% block js %}
<script language="JavaScript">
$(function () {
    {## ajax 刷新#}
    $('.captcha').click(function(){
        {#console.log('click');#}
         $.getJSON("/captcha/refresh/",
                  function(result){
             $('.captcha').attr('src', result['image_url']);
             $('#id_captcha_0').val(result['key'])
          });});
})
</script>
{% endblock %}

apps/user/templates/user_login_test.html
{% extends "base_tmp.html" %}

{% block css %}

<link rel="stylesheet" href="/static/base/css/msg_style.css">
{% endblock %}

{% block content %}

    <!--内容-->
<div class="container" style="margin-top:76px">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-info">

                <div class="panel-heading">
                    <h3 class="panel-title">
                        <span class="glyphicon glyphicon-list-alt"></span>&nbsp;会员登录</h3>
                </div>

                <div class="panel-body">

                    <form action="{% url 'user:login' %}" method="post" class="smart-green">
                        <h1>用户登录</h1>
                        {{ form.as_p }}



                        {% if messages %}
                           <ul>
                              {% for msg in messages %}
                                <li style="color: red">{{msg.message}}</li>
                               {% endfor %}
                           </ul>
                        {% endif %}

                        <div class="success-msg"></div>
                        <label>
                            <span>&nbsp;</span>
                            <input type="submit" class="button" value="提交登录"/>
                        </label>

                        <label>
                            <span>忘记账号？请点击 <a href="{% url 'user:register' %}">注册</a></span>
                        </label>

                    </form>

                </div>
            </div>
        </div>

    </div>
</div>
<!--内容-->
    
{% endblock %}

{% block js %}
<script language="JavaScript">
$(function () {
    {## ajax 刷新#}
    $('.captcha').click(function(){
        console.log('click');
         $.getJSON("/captcha/refresh/",
                  function(result){
             $('.captcha').attr('src', result['image_url']);
             $('#id_captcha_0').val(result['key'])
          });});
})
</script>
{% endblock %}

apps/user/templates/user_register.html
{% extends "base_tmp.html" %}

{% block css %}

<link rel="stylesheet" href="/static/base/css/msg_style.css">
{% endblock %}

{% block content %}

<!--内容-->
<div class="container" style="margin-top:76px">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title"><span class="glyphicon glyphicon-list-alt"></span>&nbsp;会员注册</h3>
                </div>
                <div class="panel-body">

                    <form action="{% url 'user:register' %}" method="post" class="smart-green">

                        <h1>用户注册</h1>

                        <!--
                        {{ form.as_p }}
                        -->

                       {{ form.username.label }}
                       {{ form.username }}
                        <a style="color: red">{{ form.username.errors }}</a>

                        {{ form.password.label }}
                       {{ form.password }}
                       <a style="color: red">{{ form.password.errors }}</a>

                       {{ form.email.label }}
                       {{ form.email }}
                        {{ form.email.errors }}

                        {{ form.captcha.errors }}
                      {{ form.captcha.label_tag }}
                      {{ form.captcha }}

                         {% if messages %}
                           <ul>
                              {% for msg in messages %}
                                <li style="color: red">{{msg.message}}</li>
                               {% endfor %}
                           </ul>
                        {% endif %}

                        <div class="success-msg"></div>
                        <label>
                            <span>&nbsp;</span>
                            <input type="submit" class="button" value="提交注册"/>
                        </label>

                        <label>
                            <span>已有账号？请点击 <a href="{% url 'user:login' %}">登录</a></span>
                        </label>

                    </form>

                </div>
            </div>
        </div>

    </div>
</div>
<!--内容-->

{% endblock %}

{% block js %}
<script language="JavaScript">
$(function () {
    {## ajax 刷新#}
    $('.captcha').click(function(){
        console.log('click');
         $.getJSON("/captcha/refresh/",
                  function(result){
             $('.captcha').attr('src', result['image_url']);
             $('#id_captcha_0').val(result['key'])
          });});
})
</script>
{% endblock %}

apps/user/templates/user_register_test.html
{% extends "base_tmp.html" %}

{% block css %}

<!-- css -->
<link rel="stylesheet" type="text/css" href="http://yanshi.sucaihuo.com/modals/40/4070/demo/css/index.css">
<link href="http://yanshi.sucaihuo.com/modals/40/4070/demo/css/skitter.styles.css" type="text/css" media="all" rel="stylesheet" />


<!-- js -->
<script type="text/javascript" src="http://yanshi.sucaihuo.com/modals/40/4070/demo/js/jquery.js"></script>
<script type="text/javascript" src="http://yanshi.sucaihuo.com/modals/40/4070/demo/js/public.js"></script>
<script type="text/javascript" language="javascript" src="http://yanshi.sucaihuo.com/modals/40/4070/demo/js/jquery.easing.1.3.js"></script>
<script type="text/javascript" language="javascript" src="http://yanshi.sucaihuo.com/modals/40/4070/demo/js/jquery.skitter.min.js"></script>
{% endblock %}

{% block content %}

	<div class="content" style="margin-top: 100px">
		<div class="wid_con loginbox">
			<div class="border_box">
				<div class="box_skitter box_skitter_large">
					<ul>
						<li><img src="http://yanshi.sucaihuo.com/modals/40/4070/demo/images/login_pic01.jpg" class="cube" /></li>
{#						<li><img src="http://yanshi.sucaihuo.com/modals/40/4070/demo/images/case_bg.jpg" class="cubeRandom" /></li>#}
{#						<li><img src="http://yanshi.sucaihuo.com/modals/40/4070/demo/images/banner1.jpg" class="cubeStop" /></li>#}
					</ul>
				</div>
			</div>
			<form class="login_con" action="{% url 'user:login' %}" method="post">
				<h1>用户注册</h1>
				<div class="text_box">
					<div>
						<div><i><img src="http://yanshi.sucaihuo.com/modals/40/4070/demo/images/icon01.png"></i>{{ form.username }}</div>
						<div><i><img src="http://yanshi.sucaihuo.com/modals/40/4070/demo/images/icon02.png"></i>{{ form.password }}</div>
                        <div><i><img src="http://yanshi.sucaihuo.com/modals/40/4070/demo/images/icon02.png"></i>{{ form.email }}</div>
						<div class="yzm">
							<i><img src="http://yanshi.sucaihuo.com/modals/40/4070/demo/images/icon03.png"></i>{{ form.captcha.TextInput }}
{#							<label>{{ form.captcha }}</label>#}
						</div>
						<h3>
							<a href="#">忘记密码？</a>
							<a href="#">没有帐号？免费注册！</a>
						</h3>
						<button type="submit">登 录</button>
					</div>
				</div>
			</form>
		</div>
	</div>




{#<!--内容-->#}
{#<div class="container" style="margin-top:76px">#}
{#    <div class="row">#}
{#        <div class="col-md-12">#}
{#            <div class="panel panel-info">#}
{#                <div class="panel-heading">#}
{#                    <h3 class="panel-title"><span class="glyphicon glyphicon-list-alt"></span>&nbsp;会员注册</h3>#}
{#                </div>#}
{#                <div class="panel-body">#}
{##}
{#                    <form action="{% url 'user:register' %}" method="post" class="smart-green">#}
{##}
{#                        <h1>用户注册</h1>#}
{##}
{#                        <!--#}
{#                        {{ form.as_p }}#}
{#                        -->#}
{##}
{#                       {{ form.username.label }}#}
{#                       {{ form.username }}#}
{#                        <a style="color: red">{{ form.username.errors }}</a>#}
{##}
{#                        {{ form.password.label }}#}
{#                       {{ form.password }}#}
{#                       <a style="color: red">{{ form.password.errors }}</a>#}
{##}
{#                       {{ form.email.label }}#}
{#                       {{ form.email }}#}
{#                        {{ form.email.errors }}#}
{##}
{#                        {{ form.captcha.errors }}#}
{#                      {{ form.captcha.label_tag }}#}
{#                      {{ form.captcha }}#}
{##}
{#                         {% if messages %}#}
{#                           <ul>#}
{#                              {% for msg in messages %}#}
{#                                <li style="color: red">{{msg.message}}</li>#}
{#                               {% endfor %}#}
{#                           </ul>#}
{#                        {% endif %}#}
{##}
{#                        <div class="success-msg"></div>#}
{#                        <label>#}
{#                            <span>&nbsp;</span>#}
{#                            <input type="submit" class="button" value="提交注册"/>#}
{#                        </label>#}
{##}
{#                        <label>#}
{#                            <span>已有账号？请点击 <a href="{% url 'user:login' %}">登录</a></span>#}
{#                        </label>#}
{##}
{#                    </form>#}
{##}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{##}
{#    </div>#}
{#</div>#}
{#<!--内容-->#}

{% endblock %}

{% block js %}

    <script type="text/javascript" language="javascript">
	$(document).ready(function() {
		$('.box_skitter_large').skitter({
			theme: 'clean',
			numbers_align: 'center',
			progressbar: false,
			dots: true,
			preview: true,
			stop_over:false,
		});
	});
</script>


{% endblock %}