apps/analyze/urls.py
from django.conf.urls import url
from analyze import views

urlpatterns = [
	url(r'^index/$', views.IndexHandler,name='index'),
	url(r'^art/', views.AnalyzeArtHandler,name='analyze_art'),
	url(r'^order/', views.AnalyzeOrderHandler,name='analyze_order'),
]

dj_Book/urls.py
from django.conf.urls import url,include
import xadmin
from django.views.generic.base import RedirectView

from apps.order.pay_helper import pay

urlpatterns = [
    url('xadmin/', xadmin.site.urls),
    url(r'^$',  RedirectView.as_view(url="/book/index"),name='index'),
    url(r'^book/', include("book.urls",namespace='art')),
    url(r'^comment/', include("comment.urls",namespace='comment')),
    url(r'^message/', include("message.urls",namespace='message')),
    url(r'^order/', include("order.urls",namespace='order')),
    url(r'^cart/', include("cart.urls",namespace='cart')),
    url(r'^user/', include("user.urls",namespace='user')),
    url(r'^apis/', include("apis.urls")),
    url(r'^analyze/', include("analyze.urls",namespace='analyze')),
    url(r'^search/', include('haystack.urls',namespace='search')),
    url(r'^captcha', include('captcha.urls')),
    url(r'^ueditor/',include('DjangoUeditor.urls'))
]

extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

apps/analyze/models.py
from django.db import models

# Create your models here.

apps/analyze/views.py
from django.shortcuts import render
from dj_Book.utils import check_user_login
from apps.book.models import Tag,Art
from apps.order.models import OrderItem, ProductOrder
import json

@check_user_login
def IndexHandler(request):
    return render(request, "analyze_index.html")

from django.db.models import Count, Q


def AnalyzeArtHandler(request):
    tags = Tag.objects.filter(t_flag = 0).order_by('id')
    arts = Art.objects.all()
    nums = []
    hots = [1,2,3,4,5,6,7,8,9,10]

    for tag in tags:
        arts = tag.art_set.all()
        arts_num = arts.count()
        tag.arts_num = arts_num
        nums.append(arts_num)
        # 分组函数, 用于实现聚合groupby查询前面的values写的是谁，就group谁,通过计算得到的聚合值的字典
        tag.hot_nums = arts.order_by('hot').values('hot').annotate(hot_num=Count('id'))
        # 通过计算得到的聚合值的字典
        # users = Arts.aggregate(hot_num=Count('hot'))

    context = {
        'tags':tags,
        'nums':nums,
        'hot':hots
    }
    return render(request, "analyze_art.html",context=context)


def AnalyzeOrderHandler(request):
    user = request.session.get("muser")
    uid = user.id
    orders = ProductOrder.objects.order_by('-order_time').filter(user_id=uid)
    items = OrderItem.objects.all().distinct()
    for order in orders:
        order.items = OrderItem.objects.filter(order_id=order.id)
        order.price = 0
        for order.item in order.items:
            order.item.art = Art.objects.filter(id=order.item.product_id).first()
            order.item.price = int(order.item.art.a_price) * int(order.item.quantity)
            order.price += order.item.price



    context = {
        'orders': orders,
        'user': user,
        'items':items
    }
    return render(request, "analyze_order.html", context)

apps/analyze/templates/analyze_art.html
{% extends "analyze_base.html" %}
{% load staticfiles %}


{% block content %}

<div id="page-wrapper">

    <div class="row">
        <div class="col-lg-12">
            <h3 class="page-header">统计图表</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="container" id="container_pic_module_column"></div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="container" id="container_pic_module_pie"></div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="container" id="container_pic_module_3Dcloum"></div>
        </div>
    </div>

</div>
{% endblock %}


{% block js %}
<script src="{% static 'hchart/highcharts.js' %}"></script>
<script src="{% static 'hchart/modules/exporting.js' %}"></script>
<script src="{% static 'hchart/highcharts-3d.js' %}"></script>
<script>
   $(function () {
        $('#container_pic_module_column').highcharts({
            chart: {
                type: 'column'
            },
            title: {
                text: '按标签分类-柱形图'
            },
            xAxis: {
                categories: [
                    {% for tag in tags %}
                        "{{ tag.t_name }}",
                    {% endfor %}
                    ]
                 },
            yAxis: {
                min: 0,
                alternateGridColor: '#FDFFD5',
                title: {
                    text: '书籍数量'
                }
            },
            {#针对不同类型图表的配置#}
            plotOptions: {
                column: {
                    pointPadding: 0.2,
                    borderWidth: 0
                }
            },
            series: [{
                name: '文章数量',
                data: {{nums}}
            }]
        });


        $('#container_pic_module_pie').highcharts({
            chart: {
                type: 'pie'
            },
            title: {
                text: '按标签分类-圆饼图'
            },
            {#数据点提示框，当鼠标滑过某点时，以框的形式提示改点的数据，比如该点的值，数据单位等#}
            tooltip: {
                pointFormat: '{series.name}:<b>{point.percentage:.1f}%</b>'
            },
            {#数据列，图表上一个或多个数据系列，比如图表中的一条曲线，一个柱形#}
            series: [{
                type: 'pie',
                name: '文章百分比',
                data:
                    [
                        {% for tag in tags %}
                            ["{{tag.t_name}}", {{tag.arts_num}}],
                        {% endfor %}
                    ]
            }]
        });

        $('#container_pic_module_3Dcloum').highcharts({
            chart: {
                type: 'column',
                options3d: {
                    enabled: true,
                    alpha: 15,
                    beta: 15,
                    viewDistance: 25,
                    depth: 40
                },
                marginTop: 80,
                marginRight: 40
            },
            title: {
                text: '以评分划分的标签的文章总量'
            },
            xAxis: {
                categories: [1,2,3,4,5,6,7,8,9,10]
            },
            yAxis: {
                allowDecimals: false,
                min: 0,
                title: {
                    text: '文章数量'
                }
            },
            tooltip: {
                headerFormat: '<b>{point.key}</b><br>',
                pointFormat: '<span style="color:{series.color}">\u25CF</span> {series.name}: {point.y} / {point.stackTotal}'
            },
            plotOptions: {
                column: {
                    stacking: 'normal',
                    depth: 40
                }
            },
            series: [
                {% for tag in tags %}
                    {
                        name: '{{ tag.t_name }}',
                        data: [
                            {% for hot_num in tag.hot_nums %}
                                {{ hot_num.hot_num }},
                            {% endfor %}
                        ],
                        {#stack: 'male'#}
                    },
                {% endfor %}

            ]
        })

    });

</script>

{% endblock %}

apps/analyze/templates/analyze_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>精选美文统计</title>

    <link rel="stylesheet" type="text/css" href="{% static 'ui/themes/default/easyui.css' %}">
   <link rel="stylesheet" type="text/css" href="{% static 'ui/themes/icon.css' %}">
   <link rel="stylesheet" type="text/css" href="{% static 'ui/demo/demo.css' %}">
   <script type="text/javascript" src="{% static 'ui/jquery.min.js' %}"></script>
   <script type="text/javascript" src="{% static 'ui/jquery.easyui.min.js' %}"></script>
    <link rel="shortcut icon" href="{% static 'bootstrap/logo/logo.png' %}">
    <link href="{%  static 'admin/bower_components/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{%  static 'admin/bower_components/metisMenu/dist/metisMenu.min.css' %}" rel="stylesheet">
    <link href="{%  static 'admin/dist/css/sb-admin-2.css' %}" rel="stylesheet">
    <link href="{%  static 'admin/bower_components/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet"
          type="text/css">
    <link href="{% static 'admin/css/common.css' %}" type="text/css" rel="stylesheet">
    <style>
        .page-header{
            margin:12px;
        }
    </style>
</head>
  {% block css %}{% endblock %}
<body>
<div id="wrapper">
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">下拉菜单</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'analyze:index' %}"><img src="{%  static 'base/images/logo.png' %}" style="width:18px;height:18px;display:inline-block;">&nbsp;小说统计平台</a>
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    {% if request.session.muser %}
                        <li><a href="/xadmin"><i class="fa fa-user fa-fw"></i> {{request.session.muser}}</a>
                        </li>
                    {% endif %}
                    <li class="divider"></li>
                    <li><a href="/art/logout"><i class="fa fa-sign-out fa-fw"></i> 退出</a>
                    </li>
                </ul>
            </li>
        </ul>
        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li>
                        <a href="#"><i class="fa fa-tag" aria-hidden="true"></i> 模型管理<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="{% url 'art:index' %}"><i class="fa fa-file-text" aria-hidden="true"></i> 精选美文</a>
                            </li>
                            <li>
                                <a href="/xadmin/"><i class="fa fa-file-text" aria-hidden="true"></i> 数据管理</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-tag" aria-hidden="true"></i> 数据统计<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">

                            <li>
                                <a href="{% url 'analyze:analyze_art' %}"><i class="fa fa-filter" aria-hidden="true"></i> 文章分析</a>
                                <a href="{% url 'analyze:analyze_order' %}"><i class="fa fa-filter" aria-hidden="true"></i> 订单分析</a>
                            </li>
                            <!--
                             <li>
                                <a href="/art/lines"><i class="fa fa-vimeo-square" aria-hidden="true"></i> 线状数据统计 </a>
                            </li>
                            -->

                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}{% endblock %}

</div>

<script src="{%  static 'admin/bower_components/jquery/dist/jquery.min.js' %}"></script>
<script src="{%  static 'admin/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script src="{%  static 'admin/bower_components/metisMenu/dist/metisMenu.min.js' %}"></script>
<script src="{%  static 'admin/dist/js/sb-admin-2.js' %}"></script>

<script type="text/javascript" src="{%  static 'admin/ueditor/ueditor.config.js' %}"></script>
<script type="text/javascript" src="{%  static 'admin/ueditor/ueditor.all.js' %}"></script>
<script type="text/javascript" src="{%  static 'admin/ueditor/lang/zh-cn/zh-cn.js' %}"></script>


{% block js %}{% endblock %}

</body>

</html>

apps/analyze/templates/analyze_index.html
{% extends "analyze_base.html" %}

{% block content %}
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h3 class="page-header">文章管理/文章列表</h3>
            </div>
        </div>
        <h1 style="color: green"> 欢迎来到爱尚书城 </h1>
        </div>

    </div>

{% endblock %}

apps/analyze/templates/analyze_order.html
{% extends "analyze_base.html" %}

{% load staticfiles %}
{% block content %}

<script src="{% static 'hchart/highcharts.js' %}"></script>
<script src="{% static 'hchart/modules/exporting.js' %}"></script>

<div id="page-wrapper">

        <div class="row">
            <div class="col-lg-12">
                <h3 class="page-header">统计图表</h3>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div id="container"></div>
            </div>
        </div>

</div>
{% endblock %}


{% block js %}

    <script>
        $(function () {
            var chart = Highcharts.chart('container', {
                title: {
                    text: '订单混合图表'
                },
                xAxis: {
                    categories: [
                        {% for order in orders %}
                            "订单{{ order.order_id }}"
                        {% endfor %}

                    ]
                },
                plotOptions: {
                    series: {
                        stacking: 'normal'
                    }
                },
                labels: {
                    items: [{
                        html: '订单价格',
                        style: {
                            left: '100px',
                            top: '18px',
                            color: (Highcharts.theme && Highcharts.theme.textColor) || 'black'
                        }
                    }]
                },
                series: [
                    {% for item in items %}
                    {
                    type: 'column',
                    name: '{{ item.name }}',
                    {#订单中的每个商品个数#}
                    data: [3, 2, 1, 3, 4]
                    },
                    {% endfor %}


                {
                type: 'spline',
                name: '平均值',
                data: [
                    {% for order in orders %}
                        {{ order.avg }}
                    {% endfor %}
                ],
                marker: {
                    lineWidth: 2,
                    lineColor: Highcharts.getOptions().colors[3],
                    fillColor: 'white'
                }
                }, {
                    type: 'pie',
                    name: '每个订单总的价格',
                    data: [
                        {% for order in orders %}
                            {
                            name: '定单号{{ order.order_id }}',
                            y:{{ order.price }},
                            color: Highcharts.getOptions().colors[{{ order.id }}] // Jane's color
                            }
                        {% endfor %}

                    ],
                    center: [100, 80],
                    size: 100,
                    showInLegend: false,
                    dataLabels: {
                        enabled: false
                    }
                }]
            });
        })
    </script>

{% endblock %}