apps/book/urls.py
from django.conf.urls import url
from apps.book import views
from apps.book.test import test_param

urlpatterns = [
	url(r"^index/$", views.IndexHandler,name='index'),
	url(r'^classify/$', views.ClassifyHandler,name='classify'),
	url(r'^detail/$', views.DetailHandler,name='detail'),
	url(r'^capter/$', views.ArtCapterHandler,name='capter'),
	url(r'^test_param/(?P<art_pk>[0-9]+)/$', test_param, name="param"),
]

apps/cart/urls.py
from django.conf.urls import url
from apps.cart import views

urlpatterns = [
    url(r'^cart/view/$', views.ViewCartHandler,name='view'),
	url(r'^cart/add/$', views.AddCartHandler,name='add'),
	url(r'^cart/sub/$', views.SubCartHandler,name='sub'),
	url(r'^cart/clean/$', views.CleanCartHandler,name='clean'),
]

apps/comment/urls.py
from django.conf.urls import url, include
from apps.comment import views

app_name = "comments"

urlpatterns = [
	url(r"^book/(?P<art_pk>[0-9]+)/$", views.art_comment, name="art_comm")
]

dj_Book/urls.py
from django.conf.urls import url,include
import xadmin
from django.views.generic.base import RedirectView

from apps.order.pay_helper import pay

urlpatterns = [
    url('xadmin/', xadmin.site.urls),
    url(r'^$',  RedirectView.as_view(url="/book/index"),name='index'),
    url(r'^book/', include("book.urls",namespace='art')),
    url(r'^comment/', include("comment.urls",namespace='comment')),
    url(r'^message/', include("message.urls",namespace='message')),
    url(r'^order/', include("order.urls",namespace='order')),
    url(r'^cart/', include("cart.urls",namespace='cart')),
    url(r'^user/', include("user.urls",namespace='user')),
    url(r'^apis/', include("apis.urls")),
    url(r'^analyze/', include("analyze.urls",namespace='analyze')),
    url(r'^search/', include('haystack.urls',namespace='search')),
    url(r'^captcha', include('captcha.urls')),
    url(r'^ueditor/',include('DjangoUeditor.urls'))
]

extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

apps/book/models.py
from django.db import models
import django.utils.timezone as timezone
from dj_Book.settings import  DB_FIELD_VALID_CHOICES
from DjangoUeditor.models import UEditorField
import time, datetime

'''
小说标签类
'''
class Tag(models.Model):
	id = models.CharField(primary_key=True,max_length=20)
	t_name = models.CharField(max_length=20, verbose_name="文章标签")
	t_url = models.CharField(max_length=255,verbose_name="标签链接")
	t_createtime = models.DateTimeField(default=timezone.now,  db_index=True, verbose_name="创建时间")
	#t_createtime = models.IntegerField(default=datetime.datetime.now(),  verbose_name="创建时间")
	t_flag = models.IntegerField(default=0, verbose_name="控制字段", choices=DB_FIELD_VALID_CHOICES)

	def __str__(self):
		return self.t_name

	class  Meta:
		verbose_name = "标签"
		verbose_name_plural = verbose_name
		db_table = "tag"
		ordering = ["-t_createtime"]    #按照创建时间降序

'''
小说介绍信息
'''
class Art(models.Model):
	id = models.CharField(primary_key=True,max_length=20)
	tag = models.CharField(max_length=20, null=True)
	a_title = models.CharField(max_length=100, verbose_name="文章标题")
	a_info = models.CharField(max_length=200, verbose_name="文章描述")
	a_author = models.CharField(max_length=50,verbose_name="文章作者")
	a_img_url = models.CharField(max_length=255)
	a_img_url_figer = models.CharField(max_length=255)
	a_content_ue = UEditorField(verbose_name="文章内容", width=800, height=400,
							 imagePath="media/arts_ups/ueditor/",
							 filePath="media/arts_ups/ueditor/",
							 blank=True, null=True, toolbars="full", default='')
	a_createtime = models.DateTimeField(default=timezone.now, db_index=True,verbose_name="添加时间")
	#a_createtime = models.IntegerField(default=int(time.time()),  verbose_name="添加时间")
	t_id = models.ForeignKey(Tag, verbose_name="关联文章标签",db_column='t_id')
	a_price = models.IntegerField(default=0, null=True, verbose_name="单价")
	a_flag = models.IntegerField(default=0,  verbose_name="控制字段", choices=DB_FIELD_VALID_CHOICES)
	operator = models.ForeignKey("auth.User", default=1, verbose_name="api操作者",db_column='operator',null=True)
	hot = models.IntegerField(default=0,verbose_name="热度", null=True)


	def __str__(self):
		return self.a_title


	class Meta:
		verbose_name = "小说"
		verbose_name_plural = verbose_name
		db_table = "art"
		ordering = ["-a_createtime"]  # 按照创建时间降序


'''
小说的内容信息
'''
class Content(models.Model):
	id = models.CharField(primary_key=True, max_length=20)
	a_content = models.TextField(verbose_name="小说内容",null=True)
	a_id = models.ForeignKey(Art, verbose_name="小说", db_column='a_id')
	class Meta:
		db_table = "art_content"
		verbose_name = "小说内容"
		verbose_name_plural = verbose_name

'''
小说的章节信息
'''
class Chapter(models.Model):
	id = models.CharField(primary_key=True,max_length=20)
	a_id = models.ForeignKey(Art, verbose_name="小说",db_column='a_id')
	title = models.CharField(max_length=100, verbose_name="章节标题")
	content = models.TextField(verbose_name="小说章节内容",null=True)
	create_time = models.DateTimeField(default=timezone.now, db_index=True,verbose_name="添加时间")
	#create_time = models.IntegerField(default=int(time.time()), db_index=True, verbose_name="添加时间")

	class Meta:
		db_table = "art_chapter"
		verbose_name = "小说章节"
		verbose_name_plural = verbose_name

apps/book/views.py
import random

from django.core.paginator import Paginator
from django.http import HttpResponse

from dj_Book import utils
from dj_Book.settings import logger
from apps.book import models
from apps.comment import forms
from apps.comment.models import Comment
from apps.book.models import Tag,Art

'''
首页卡片式页面展示：
      接口URL：  /book/index?page=1&t=1
     Models层中类的定义也属于接口范围
     方法：GET
      输入参数说明：
          page:   第几页
          t:  标签类别，整数标识  eg: 0--全部   1--爱情小说  2—科幻小说
      输出：
            渲染首页卡片式页面
'''

'''
	arts = Art.objects.all()
	for art in arts:
		tag = art.t_id.t_name
		art.tag = tag
		art.save()
	return HttpResponse('修改成功')
'''

def IndexHandler(request):
	logger.debug("IndexHandler:enter.")
	url = request.path
	t = int(request.GET.get('t', 0))
	page = int(request.GET.get('page', 1))
	tags = models.Tag.objects.filter(t_flag = 0)  #获取未删除的标签
	if t == 0:
		total = models.Art.objects.filter(a_flag = 0).count()
	else:
		total = models.Art.objects.filter(a_flag=0, t_id=t).count()
	# logger.info(f"IndexHandler, t:{t}, page:{page}, total:{total}")
	context = dict(
		pagenum = 1,
		total = 0,
		prev = 1,
		next = 1,
		pagerange = range(1, 2),
		data = [],
		url = url,
		tags = tags,
		page = page,
		t = t,
	)
	shownum = 12
	if total > 0:
		import math
		pagenum = int(math.ceil(total / shownum))
		#logger.warn(f"IndexHandler, pagenum: {pagenum}")
		if page < 1:
			url = url + "?page=1&t=%d" % t
			return HttpResponseRedirect(url)
		if page > pagenum:
			url = url + "?page=%d&t=%d" % (pagenum, t)
			return HttpResponseRedirect(url)
		offset = (page - 1) * shownum
		if t == 0:
			data = models.Art.objects.filter(a_flag=0)[offset:offset + shownum]
		else:
			data = models.Art.objects.filter(t_id=t, a_flag=0)[offset:offset + shownum]
		key = "page:%d:t:%d" % (page, t)

		utils.store_rds_str(key, data)

		btnum = 5
		if btnum > pagenum:
			firtpage = 1
			lastpage = btnum
		else:
			if page == 1:
				firtpage = 1
				lastpage = btnum
			else:
				firtpage = page - 2
				lastpage = page + btnum - 2
				if firtpage < 1:
					firtpage = 1
				if lastpage > pagenum:
					lastpage = pagenum
		prev = page - 1
		next = page + 1
		if prev < 1:
			prev = 1
		if next > pagenum:
			next = pagenum

		context = dict(
			pagenum=pagenum,
			total=total,
			prev=prev,
			next=next,
			pagerange=range(firtpage, lastpage + 1),
			data=data,
			url=url,
			tags=tags,
			page=page,
			t=t,
		)
	print(context)
	return render(request, "book_index.html", context=context)
	#return HttpResponse("主页面")


'''
详情页面功能：
       接口URL：  /book/detail?id=7
      方法：GET
      输入参数说明：
          id： 文章id，（点击某一个具体的文章，传入文章id)
     输出：
          渲染详情页面
'''

def DetailHandler(request):
	a_id = int(request.GET.get("id", 0))
	if a_id == 0:
		return HttpResponseRedirect("/book/index")
	#获取小说详情
	art_queryset = models.Art.objects.get(id = a_id)

	#获取小说对应的章节
	art_capters = models.Chapter.objects.filter(a_id=a_id)

	#获取评论表单
	comment_form = forms.CommentForm()
	comment_list = Comment.objects.filter(art_id = a_id)
	context = dict(
		art = art_queryset,
		art_capters = art_capters,
		form = comment_form,
		comment_list = comment_list,
		comment_count = comment_list.count(),
	)

	return render(request, "book_detail.html", context=context)


'''
小说章节
/book/capter?id=capter_id
'''
def ArtCapterHandler(request):
	capter_id = int(request.GET.get("id", 0))
	if capter_id == 0:
		return  DetailHandler(request)
	art_capter = models.Chapter.objects.get(id = capter_id)
	context = dict(
		art_capter = art_capter
	)
	return render(request, "book_captcha.html", context=context)


from django.shortcuts import render, HttpResponseRedirect
from .models import Tag, Art
from django.db.models import Q

'''
页面分类功能：
'''
def ClassifyHandler(request):

	arts = Art.objects.all()
	arts_count = arts.count()
	# 获取所有的标签
	tags = Tag.objects.filter(t_flag=0)
	tid = '0'
	hot= None
	price = None
	time = None

	# 根据标签进行筛选
	tid = request.GET.get('tid','0')
	if tid != '0':
		arts = arts.filter(t_id=tid)
		arts_count = arts.count()

	# 1 升序  0 降序
	# 根据热度进行筛选
	hot = request.GET.get('hot')
	a = type(hot)
	if hot == '1':
		arts = arts.order_by('hot')
	elif hot == '0':
		arts = arts.order_by('-hot')

	# 根据价格进行筛选
	# 排序
	price = request.GET.get('price')
	if price == '1':
		arts = arts.order_by('a_price')
	elif price == '0':
		arts = arts.order_by('-a_price')

	# 价格
	min_price = request.GET.get('min_price')
	max_price = request.GET.get('max_price')
	if min_price and max_price:
		arts = arts.filter(a_price__range=[int(min_price),int(max_price)])
		arts_count = arts.count()



	# 根据时间进行筛选
	time = request.GET.get('time')
	if time == '1':
		arts = arts.order_by('a_createtime')
	elif time == '0':
		arts = arts.order_by('-a_createtime')


	"""分页"""
	paginator = Paginator(arts, 12)
	page = request.GET.get('page')
	if page:
		page = int(page)
	else:
		page = 1
	if page > paginator.num_pages:
		page = 1
	arts_page = paginator.page(page)
	num_pages = paginator.num_pages
	if num_pages < 5:
		# 1-num_pages
		pages = range(1, num_pages + 1)
	elif page <= 3:
		pages = range(1, 6)
	elif num_pages - page <= 2:
		# num_pages-4, num_pages
		pages = range(num_pages - 4, num_pages + 1)
	else:
		# page-2, page+2
		pages = range(page - 2, page + 3)

	# 组织模板数据
	context = {
		'tags': tags,
		'pages': pages,
		'arts_page': arts_page,
		'arts_count':arts_count,
		'tid':tid,
		'hot':hot,
		'price':price,
		'time':time
	}
	return render(request, "book_classify.html", context=context)

def RecommendHandler(request):
	pass

apps/book/templates/book_banner.html
<div class="container" id="myCarousel" style="margin-top:80px">
		<!-- 轮播图容器 -->
		<div id="carousel-example-generic" class="carousel slide">
			<!-- 轮播图上的圆圈链接 -->
			<ol class="carousel-indicators radiou">
				<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
				<li data-target="#carousel-example-generic" data-slide-to="1"></li>
				<li data-target="#carousel-example-generic" data-slide-to="2"></li>
                <li data-target="#carousel-example-generic" data-slide-to="3"></li>
			</ol>
			<!-- 轮播图具体内容 -->
			<div class="carousel-inner">
				<div class="item active">
					<img src="/static/images/fengmian1.jpeg" style="background-size:cover; height: 300px; width:1200px">
					<!-- 图上文字 -->
					<div class="carousel-caption">
						<h4>美丽俏佳人</h4>
						<p>美丽俏佳人</p>
					</div>
				</div>
				<div class="item">
					<img src="/static/images/shanhaijing.jpeg" style="background-size:cover; height: 300px; width:1200px">
					<!-- 图上文字 -->
					<div class="carousel-caption">
						<h4>山海经</h4>
						<p>山海经 密码</p>
					</div>
				</div>
				<div class="item">
                    <img src="/static/images/hudie.jpeg" style="background-size:cover; height: 300px; width:1200px">
					<!-- 图上文字 -->
					<div class="carousel-caption">
						<h4>新鸳鸯蝴蝶梦</h4>
						<p>新鸳鸯蝴蝶梦 名著</p>
					</div>
				</div>
                <div class="item">
                    <img src="/static/images/liangcheng.jpeg" style="background-size:cover; height: 300px; width:1200px">
					<!-- 图上文字 -->
					<div class="carousel-caption">
						<h4>凉城以北</h4>
						<p>凉城以北</p>
					</div>
				</div>
			</div>
			<!-- 轮播图上的向前一图切换链接 -->
			<a href="#carousel-example-generic" data-slide="prev" class="left carousel-control">
				<span class="glyphicon glyphicon-chevron-left"></span>
			</a>
			<!-- 轮播图上的向后一图切换链接 -->
			<a href="#carousel-example-generic" data-slide="next" class="right carousel-control">
				<span class="glyphicon glyphicon-chevron-right"></span>
			</a>
		</div>
	</div>

apps/book/templates/book_captcha.html
{% extends "base_tmp.html" %}

{% block content %}
<!--内容-->
<div class="container" style="margin-top:76px">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title"><span class="glyphicon glyphicon-list-alt"></span>{{art_capter.art.a_title}}  章节详情</h3>
                </div>
                <div class="panel-body">
                    <h1 class="text-center">{{ art_capter.title }}</h1>
                    <div style="color: green;" align="center">
                        时间:<span>{{art_capter.create_time}}</span>
                    </div>
                    <br>

                    <span>{{art_capter.content}}</span>

                </div>


            </div>
        </div>

    </div>


</div>
<!--内容-->
{% endblock %}

apps/book/templates/book_classify.html
{% extends "base_tmp.html" %}


{% block content %}
<div class="container" style="margin-top:76px">
    <div class="row wow fadeIn" data-wow-delay="0.6s">
        {#    分类条件栏    #}
        <div class="col-md-12 table-responsive">
            <table class="table text-left table-bordered" id="arttags">
                <tr>
                    <td class="bg-primary"><a href="{% url 'art:classify' %}?tid=0"><h5 style="color: white">全部类型</h5></a></td>
                    <td>
                        <ul class="list-inline ">
                        {% for tag in tags %}
                            <li><a class="label label-info" href="?tid={{ tag.id }}&hot={{ hot }}&price={{ price }}&time={{ time }}"><span class="glyphicon glyphicon-tag"></span>{{tag.t_name}}</a></li>
                        {% endfor %}
                    </ul>
                    </td>
                </tr>

                <tr>
                    <td class="bg-primary"><h5 >热度排序</h5></td>
                    <td>
                        <ul class="list-inline ">
                            <li><a  class="label label-info " href="?hot=0&price={{ price }}&time={{ time }}&tid={{ tid }}"><span class="glyphicon glyphicon-tag"></span>由高到低</a></li>
                            <li><a class="label label-info" href="?hot=1&price={{ price }}&time={{ time }}&tid={{ tid }}"><span class="glyphicon glyphicon-tag"></span>由低到高</a></li>
                        </ul>
                    </td>
                </tr>

                <tr>
                    <td class="bg-primary"><h5 >价格排序</h5></td>
                    <td>
                        <ul class="list-inline ">
                            <li><a class="label label-info" href="?price=0&hot={{ hot }}&time={{ time }}&tid={{ tid }}"><span class="glyphicon glyphicon-tag"></span>由高到低</a></li>
                            <li><a class="label label-info" href="?price=1&hot={{ hot }}&time={{ time }}&tid={{ tid }}"><span class="glyphicon glyphicon-tag"></span>由低到高</a></li>
                            <li><form action="{% url 'art:classify' %}?tid={{ tid }}"><span>价格区间:&nbsp</span><input type="text"  style="width: 50px;" placeholder="10" name="min_price"><span>-</span><input type="text"  style="width: 50px;" placeholder="50" name="max_price"><button type="submit" class="bg-info">搜索</button></form></li>
                        </ul>
                    </td>
                </tr>

                <tr>
                    <td class="bg-primary"><h5 >时间排序</h5></td>
                    <td>
                        <ul class="list-inline ">
                            <li><a class="label label-info" href="?time=0&hot={{ price }}&price={{ price }}&tid={{ tid }}"><span class="glyphicon glyphicon-tag"></span>由高到低</a></li>
                            <li><a class="label label-info" href="?time=1&hot={{ price }}&price={{ price }}&tid={{ tid }}"><span class="glyphicon glyphicon-tag"></span>由低到高</a></li>
                        </ul>
                    </td>
                </tr>
            </table>
        </div>

        {#    分类结果栏    #}
        <div class="col-md-10">
            {% for art in  arts_page %}
                <div class="col-md-2" style="margin-bottom: 20px">
                    <div class=" text-center" style="width:150px">
                        <img src="/static/imgs/full/{{art.a_img_url_figer}}.jpg" style="width:100%;height:200px;" class="img-responsive center-block lazy" alt="">
                        <div class="" style="width:100%;">
                            <div style="color: #0f0f0f;height: 30px; font-weight: bold" class="text-center">{{art.a_title}}</div>
                            <div style="color: #0f0f0f;height: 30px; font-weight: bold" class="text-center">评分:{{ art.hot }}&nbsp;&nbsp;&nbsp;&nbsp;价格:{{ art.a_price }}元</div>
                            <div style="height: 20px;overflow:hidden;text-overflow: ellipsis;white-space: nowrap">{{art.a_info}}</div>
                        </div>
                        <div style="width: 100%" class="text-center" >
                            <a href="{% url 'art:detail' %}?id={{art.id}}" class="btn btn-primary" target="_blank" role="button" style="width: 100%"><span class="glyphicon glyphicon-eye-open"></span>&nbsp;阅读</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        {#    数据个数栏    #}
        <div class="col-md-2">
            <h4 style="color: red">商品个数:{{ arts_count }}</h4>
        </div>
        {#    分页按钮组栏    #}
        <div class="col-md-12 text-center" style="margin-top:12px;">
            <div class="text-center">
                <ul class="pagination ">
                    {% if arts_page.has_previous  %}
                        <li><a href="?page={{ arts_page.previous_page_number }}">&laquo;上一页</a></li>
                    {% else %}
                        <li class="disabled"><a>&laquo;上一页</a></li>
                    {% endif %}
                    {% for pindex in pages %}
                        <li {% if pindex == arts_page.number %}class="active"{% endif %}><a href="?page={{  pindex }}" >{{ pindex }}</a></li>
                    {% endfor %}
                    {% if arts_page.has_next %}
                        <li><a href="?page={{ arts_page.next_page_number }}">下一页&raquo;</a></li>
                    {% else %}
                        <li class="disabled"><a>下一页&raquo;</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>

{% endblock %}






{% block js %}
<script>
    $(document).ready(function(){
        $("#curtag{{t}}").attr("class","label label-danger");
    });
</script>


{% endblock %}

apps/book/templates/book_detail.html
{% extends "base_tmp.html" %}


{% block content %}
    <!--内容-->
    <div class="container" style="margin-top:76px">
        <div class="row">
            {# 主页部分#}
            <div class="col-md-8">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3 class="panel-title text-center"><span class="glyphicon glyphicon-list-alt"></span>&nbsp;小说详情</h3>
                    </div>
                    <div class="panel-body clearfix">
                        <div class="clearfix">
                            <h1 class="" style="margin-left: 60px">{{ art.a_title }}</h1>
                            <div class="pull-left" style="margin-right: 50px">
                                <img src="/static/imgs/full/{{art.a_img_url_figer}}.jpg" style="width:300px;height:400px;" class="img-responsive  lazy" alt="">
                            </div>
                             <div class="pull-left">
                                <div style="font-size: 18px;margin-bottom: 10px">书名:<span style="color: green"> {{ art.a_title }}</span></div>
                                 <div style="font-size: 18px;margin-bottom: 10px">作者:<span style="color: green"> {{ art.a_author }}</span></div>
                                 <div style="font-size: 18px;margin-bottom: 10px">价格:<span style="color: green"> {{ art.a_price }}元</span></div>
                                <div style="font-size: 18px;width: 350px;margin-bottom: 20px">内容:<span style="color: green"> {{ art.content_set.first.a_content }}</span></div>
                                 <div style="font-size: 18px" class="clearfix" >
                                     <span class="pull-left">商品数量:</span>
                                     <form class="pull-left" style="margin-left: 20px">
                                         <button type="button" class="btn_sub">-</button><input type="text" value="1" style="width: 30px;" class="good_num" id="{{ art.id }}"><button type="button" class="btn_add">+</button>
                                     </form>
                                 </div>
                                 <div class="span" style="margin-top: 20px">
                                    <a class="btn primary btn-success" type="button" id="add_cart" href="{% url 'cart:add' %}?id={{ art.id }}">加入购物车</a>
                                    <a class="btn primary btn-danger" id="buy_now" type="button" href="#">立即购买</a>
                                </div>
                             </div>
                        </div>



{#                        <div class="col-md-3">#}
{#                        </div>#}
                        <div class="col-md-9">

                            {{ art.a_content | safe }}

                        </div>

                    </div>

                    <!-- ArtsTab begin -->
                    <ul id="ArtsTab" class="nav nav-tabs" style="margin-top: 50px;">
                        <li class="active">
                            <a href="#catalog" data-toggle="tab" style="color: cadetblue;font-size: 20px;">
                                小说章节
                            </a>
                        </li>
                        <li>
                            <a href="#discuss" data-toggle="tab" style="color: cadetblue;font-size: 20px;">
                                讨论区
                            </a>
                        </li>
                    </ul>

                    <div id="ArtsTabContent" class="tab-content">
                        <div class="tab-pane fade in active" id="catalog">

                            <h3 align="center">{{ art.a_title }} 章节 </h3>
                            <ul class="list-group">
                                {% for capter in art_capters %}
                                    <a class="list-group-item"
                                       href="{% url 'art:capter' %}?id={{ capter.id }}">{{ capter.title }}</a>
                                {% endfor %}
                            </ul>

                        </div>
                        <div class="tab-pane fade" id="discuss">

                            <h3 align="center">{{ art.a_title }} 的讨论区 </h3>
                            <!--- 评论区表单 --->
                            <form action="{% url 'comment:art_comm' art.pk %}" method="post" class="comment-form">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-12">
                                        <label for="{{ form.name.id_for_label }}">名字：</label>
                                        {{ form.name }}
                                        {{ form.name.errors }}
                                    </div>
                                    <div class="col-md-12">
                                        <label for="{{ form.title.id_for_label }}">标题：</label>
                                        {{ form.title }}
                                        {{ form.title.errors }}
                                    </div>

                                    <div class="col-md-12">
                                        <label for="{{ form.text.id_for_label }}">评论：</label>
                                        <br>
                                        {{ form.text }}
                                        {{ form.text.errors }}
                                        <br>
                                        <button type="submit" class="comment-btn btn-success">发表评论</button>
                                    </div>
                                </div>    <!-- row -->
                            </form>
                            <!--- 评论区表单 --->
                            <br>

                            <div class="comment-list-pannel">
                                <h3>评论列表， 共<span>{{ comment_count }}</span>条评论</h3>
                                <hr>
                                <ul class="comment-list list-unstyled">
                                    {% for comment in comment_list %}
                                        <span class="glyphicon glyphicon-user label label-primary"> {{ comment.name }}</span>
                                        <span class="glyphicon glyphicon-time label label-success">{{ comment.created_time }}</span>
                                        <br><br>
                                        <div class="text">
                                            {{ comment.text }}
                                        </div>
                                        <hr>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <!-- ArtsTab end -->
                </div>
            </div>
            {# 推荐部分#}

            <div class="col-md-4 filebox" >
                <div class="recommend "></div>
            </div>

        </div>
    </div>
    <!--内容-->
{% endblock %}

{% block js %}
<script language="JavaScript">
    $(document).ready(function () {
        let origin_url =  $('#add_cart').attr('href');
        let change_url = origin_url + '&num=';

        {#=====购物车商品加操作=====  #}
        $('.btn_add').click(function () {
            let value = parseInt($(this).prev().val())+1;
            $(this).prev().val(value);
            $('#add_cart').attr('href',change_url + String(value));

        });

          {#=====购物车商品减操作=====  #}
        $('.btn_sub').click(function () {
            let value=parseInt($(this).next().val()) < 1 ? 0 : parseInt($(this).next().val())-1;
             $(this).next().val(value);
             $('#add_cart').attr('href',change_url + String(value));
        });

         {#=====购物车立即购买操作=====  #}
        $('#buy_now').click(function () {
            let num = $('.good_num').val() ;
            let id = $('.good_num').attr('id') ;

            window.location.href = 'http://127.0.0.1:9000/cart/cart/add/?now=now&id=' + id + '&num=' + num;
        });

    });

</script>
{% endblock %}